language: elixir
elixir:
  - 1.2.6
  - 1.3.4
  - 1.4.5
  - 1.5.1
otp_release:
  - 18.3
  - 19.3
  - 20.0
sudo: false # to use faster container based build environment
env:
  - MIX_ENV=test
install:
  - mix do local.hex --force, local.rebar --force
  - mix deps.get # need to explicitly get test deps, see mix.exs
  - mix compile
script:
  - mix test
matrix:
  exclude:
    - elixir: 1.2.6
      otp_release: 20.0
    - elixir: 1.3.4
      otp_release: 20.0
